### ISSUE TITLE
Create RtRule.ByHeader implementation 

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/http#253] opened 2020-10-19 11:32 UTC
In pypi-adapter `RtRule` by header is required, so let's create such implementation. Implementation should filter requests by header name and value, it should be possible to filter values by regexps.

**Comment by 0crat** [comment] 2020-10-19 13:30
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Closed** 2020-10-20 07:50 UTC
Labels: 0crat/role/DEV, 0crat/scope

**Comment by olenagerasimova** [comment] 2020-10-20 07:58
@rultor release, tag=`16.6`

**Comment by olenagerasimova** [comment] 2020-10-20 07:59
@rultor release, tag=`0.16.6`

**Comment by 0crat** [comment] 2020-10-20 08:07
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
